name = "sourcerer"
compatibility_date = "2026-06-19"
pages_build_output_dir = "apps/web/dist"

[[d1_databases]]
binding = "DB"
database_name = "sourcerer-db"
database_id = "2ce0fa48-be71-4319-b80f-b9cef8968aff"
migrations_dir = "migrations"
